services:
  backend:
    build: .
    env_file:
      - .env
    image: rutas-vivas:local
    container_name: guia_backend
    restart: always
    ports:
      - "5030:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

  db:
    image: postgis/postgis
    platform: linux/amd64
    container_name: campus_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  osrm:
    image: osrm/osrm-backend
    platform: linux/amd64
    container_name: osrm_server
    restart: always
    command: osrm-routed /data/campus.osrm
    volumes:
      - ./osrm-data:/data

volumes:
  pgdata:
