version: "3.8"

services:
  backend:
    image: cubilloscristian/rutas-vivas:latest
    container_name: guia_backend
    ports:
      - "5030:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True

  db:
    image: postgis/postgis
    platform: linux/amd64
    container_name: guia_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: guia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  osrm:
    image: osrm/osrm-backend
    platform: linux/amd64
    container_name: osrm_server
    command: osrm-routed /data/campus.osrm
    ports:
      - "8080:5000"
    volumes:
      - ./osrm-data:/data
