# Generated by Django 5.2.3 on 2025-07-06 23:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='default', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('emotions', models.TextField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='landmarks/main/')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('emotions', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guia.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landmarks/secondary/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to='guia.landmark')),
            ],
        ),
        migrations.AddField(
            model_name='landmark',
            name='moods',
            field=models.ManyToManyField(blank=True, to='guia.mood'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emotions', models.TextField(blank=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('landmarks', models.ManyToManyField(related_name='stations', to='guia.landmark')),
            ],
        ),
    ]
